[build]
    command = "yarn build"
    functions = "built-lambda"
    publish = "build"

[dev]
    command = "yarn start"
    publish = "build"

[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
